services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=192.168.1.16
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=notifications
      - POSTGRES_SSL_MODE=disable
    ports:
      - "8080:8080"
